### ISSUE TITLE
The duration in meeting doesn't automatically change

### ISSUE THREAD

**Issue by CostiChD** [xwikisas/application-meeting#33]
Issue: https://jira.xwiki.org/browse/XAMEETINGS-142

Steps to reproduce:

1 .Click on Meetings from Applications Panel
2. Add a new meeting with a specified Duration e.g. 1h 30 min
3. Click on Meeting again
4. Click on Calendar
5. Resize the meeting duration e.g. drag the box to have a 3h Duration
6. Click on Meetings
7. Expected results: The Duration is automatically changed in the LiveTable for that meeting.

Actual results: The Duration remains at "1h 30 min".

NOTE: The solution is to Edit the meeting, refresh the page (ctrl + f5) then press Save & View. This won't change the Duration in view mode so you have to refresh the page again for that to be changed.

**Comment by CostiChD** [comment]
NOTE 2: After resizing the meeting duration( drag in calendar overview), if you just go to that meeting page(here the value will still be the old one until you refresh the page) the duration will be updated in the livetable.

**Comment by lucaa** [comment]
Please note that all duration-related issues should be looked at together with https://jira.xwiki.org/projects/XAMEETINGS/issues/XAMEETINGS-130 - I think before we invest time in fixing the issues related to the current duration implementation we should consider migrating to a proper duration management.

**Comment by CostiChD** [comment]
An approach would be just to keep the duration property and use the custom display to show it in the livetable(from the WebHome), like it was before with the durationString property. Also (using custom display) we would need to get the duration(using 2 inputs: one for the hours and one for the minutes) in edit mode.
  I dont see the point of using an endDate property because usually meetings have a shorter duration than  24 hours and this could be done just with the duration property.
  Another thing that we should consider is that the "duration" property actually has the type Static List, even tho it keeps a number.(this is the reason why the Duration sorting does not work right now in the livetable)
  This way we can get rid of durationHour, durationMinutes, durationString, calc and hasBeenEdited properties and keep just the "duration" property.
