### ISSUE TITLE
Resizing meetings in calendar overview generates wrong duration values.

### ISSUE THREAD

**Issue by CostiChD** [xwikisas/application-meeting#34]
Steps to reproduce:

1. Create a meeting.
2. Go to Meeting.WebHome
3. Go to calendar overview(by clicking on "calendar")
4. Resize the meeting(drag) so it goes to the next column(next day).
5. Go back to your meeting page(in order to avoid reproducing https://github.com/xwikisas/application-meeting/issues/33 )
6. Go back to Meeting.WebHome.

Results: 
The meeting is going to have a wrong duration(it also can be negative).

**Comment by lucaa** [comment]
Please note that all duration-related issues should be looked together with https://jira.xwiki.org/projects/XAMEETINGS/issues/XAMEETINGS-130 - I think before we invest time in fixing the issues related to the current duration implementation we should consider migrating to a proper duration management.

**Comment by oanalavinia** [comment]
This issue was fixed due to some modifications done in #42
