### ISSUE TITLE
Warnings in the Progress log when installing Meeting Application (Pro)

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-meeting#43]
STEPS TO REPRODUCE

1. Go to Administer Wiki > Extensions > Extensions
2. Search for Meeting Application (Pro)
3. Click on Install, then Continue

EXPECTED RESULTS

The application is installed successfully without any warnings/errors.

ACTUAL RESULTS

Two warning messages are displayed in the Progress log: 

`Unexpected error when trying to find extension dependency [org.xwiki.contrib:macro-fullcalendar-ui-2.1.4] in repository [public-store-snapshots:maven:https://nexus.xwiki.com/nexus/content/repositories/public-store-snapshots/]:`

`Unexpected error when trying to find extension dependency [org.xwiki.contrib:xwiki-macro-map-2.1] in repository [public-store-snapshots:maven:https://nexus.xwiki.com/nexus/content/repositories/public-store-snapshots/]:`

Environment: Windows 10 Pro 64-bit, Edge 17, using a local instance of XWiki 10.10 on PostgreSQL 10.

![meeting_error_logs](https://user-images.githubusercontent.com/32512703/50003601-d81c6f00-ffac-11e8-8493-62f07dd446af.jpg)

**Comment by mflorea** [comment]
See my comment on https://github.com/xwikisas/application-mocca-calendar/issues/21#issuecomment-447811784

**Comment by acotiuga** [comment]
The issues is not reproducing anymore on XWiki 11.7. The progress log is clean.
