### ISSUE TITLE
Meeting calendar preview doesn't show up on Gmail

### ISSUE THREAD

**Issue by silviamacovei** [xwikisas/application-meeting#73]
A nice calendar event should be displayed as a preview, however it’s not, as seen in the attached image.

<img width="862" alt="MeetingNotificationMissingPreview" src="https://user-images.githubusercontent.com/42776453/95089362-bca7c880-072c-11eb-9582-54d38fec71d9.png">

**Comment by silviamacovei** [comment]
1.5 months later I no longer reproduce the issue, although I tested it in the same instance, with the same meeting (XWiki 11.10.5 + Chrome + GMAIL). I think you can close it for now.

**Comment by acotiuga** [comment]
I tested again on multiple versions of XWiki (9.11, 12,9) and Meeting 1.10 and I couldn't reproduce anymore.
