### ISSUE TITLE
Update the template provider for the meeting to replace the usage of the deprecated "spaces" property

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-meeting#74]
Because of this issue https://jira.xwiki.org/browse/XWIKI-18060 and the fact that the meeting template provider is using the spaces property, the behaviour of the meeting template provider is incomprehensible: the page of the template provider says there is no restriction but still, the template is not available everywhere  (see screenshots of the linked ticket).

**Comment by lucaa** [comment]
Also, please check if other applications may be in this case.
Diagram app was for a while (until its issue 172 was fixed), but other apps should get fixed as well.

**Comment by lucaa** [comment]
Note that the above fix is also bringing a behaviour change, as creationRestrictions is not 100% equivalent to spaces:
* before, the template was visible only in the Meeting space and pages could be created only in the Meeting space
* after, the template is visible anywhere, but when choosing this template the page is created in the Meeting space.

I'm fine with the new behaviour, I think it's even better (although I would check to verify that it corresponds to what other applications are doing), just making sure it's mentioned on the ticket as a consequence and a decision, rather than a side-effect.

**Comment by acotiuga** [comment]
There was no discussion about changing the behaviour, so I'm fixing it to be just the same as before. 
Also, there were some different approaches among the other applications so there is not only one rule, or a general one.
