### ISSUE TITLE
"valuex" labels appears instead of the actual status when hovering over an event in Calendar view

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-meeting#79]
Steps to reproduce:

1. Click on Meeting App from Apps Panel
2. Add some meeting events with different Statuses (In preparation, Active, Cancelled, Finished)
3. On Meetings Homepage, click on Calendar
4. Navigate to the meeting events
5. Hover with the mouse cursor over the meeting events

Expected results: The hover box displays information about the Status, Location and Description for each meeting.

Actual results: The Status displays "value1" / "value2" / "value3" / "value4" instead of the actual status. The Location and Description are displayed properly.

This reproduces on EN and FR wikis.

![Values](https://user-images.githubusercontent.com/40691112/101672987-388cfc80-3a5f-11eb-8933-666cc9d56ed4.png)

Environment: XWiki 12.6.5 with Chrome 87

**Comment by acotiuga** [comment]
This issue will be fix as part of https://jira.xwiki.org/browse/FULLCAL-62 and it should be closed when the FullCalendar dependency version will be updated.

**Comment by mflorea** [comment]
See my comment on https://github.com/xwikisas/application-meeting/issues/84#issuecomment-811919595 .
