### ISSUE TITLE
Meeting addresses with accents in the name (french) are not properly found on the map

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-meeting#8]
When making a meeting at an address like this:

"1 Avenue de Ségur, 75007 Paris"

and checking the "display map" checkbox, it does not display properly on the map: the map is displayed but the place it shows on the map is not the correct place for this address.

The reason is the accent in the name of the address, somehow the address that is being searched for is "Avenue du S".

If the address is changed to "1 Avenue de Segur, 75007 Paris" , the map is correct.

**Comment by lucaa** [comment]
I inspected a bit the network requests and apparently the problem is in the geolocator service:
https://maps.googleapis.com/maps/api/js/GeocodeService.Search?4s1%20Avenue%20de%20S%5Cu00E9gur%2C%2075007%20Paris&7sUS&9sen-US...

The parameters sent to it contain the encoded accent:

![image](https://user-images.githubusercontent.com/657716/39700661-488811ac-51fe-11e8-9db6-744451a34154.png)

and in the response the found address seems to stop at the accent:

![image](https://user-images.githubusercontent.com/657716/39700667-4e47e5f4-51fe-11e8-8b4d-0a919fe4e4ca.png)

**Comment by acotiuga** [comment]
This is a Map macro issue: https://jira.xwiki.org/browse/MAP-15. I will use this issue to commit the Map macro dependency's version update.
