### ISSUE TITLE
Meetings with \ (backslash) in names break the calendar view (no meeting is displayed on the calendar anymore)

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-meeting#82]
It's actually an issue of the calendar macro 2.2.4 which is a dependency of this application: https://jira.xwiki.org/browse/FULLCAL-58 .

The usecase that can be used to reproduce is written on the fullcalendar ticket.

**Comment by mflorea** [comment]
We need to release full calendar macro 2.2.5 and upgrade the dependency here in the meeting application.

**Comment by acotiuga** [comment]
Fixed in e5425a4b7d2801f5ac08c4b27f42f278bec3b5d0.
