### ISSUE TITLE
'Calendar loaded' message should be displayed less often at the bottom of the page (if at all)

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-meeting#85]
STEPS TO REPRODUCE

Environment: Windows 10 Pro 64bit, Chrome 87, using an instance of XWiki 12.10.2 on PostgreSQL 13, Tomcat 9.0.41, Meeting Pro 1.11.1

1. Go to Meetings app
2. Click on 'Calendar' link
3. Click on navigation buttons '<' or '>' repeatedly

EXPECTED RESULTS

'Calendar loaded' message is displayed on the bottom when first landing on the page or not displayed at all.

ACTUAL RESULTS

The message is displayed every time a navigation button is clicked and can stack up, which may degrade the user experience:

![Calendar_loaded_messages](https://user-images.githubusercontent.com/32512703/105050444-73c71600-5a76-11eb-8abb-216aa00e4dae.png)

**Comment by ignatescustefan** [comment]
After my investigation, this issue is related to the macro-fullcalendar application and needs to be fixed there.

**Comment by acotiuga** [comment]
Fixed in https://jira.xwiki.org/browse/FULLCAL-61. 
At least one notification is needed to provide feedback about calendar loading. When the arrows are used for weeks/months navigation, the loading function is called and a new set of events are displayed. The notification cannot be completely removed.

**Comment by acotiuga** [comment]
This issue should be closed when the FullCalendar dependency version will be updated.

**Comment by mflorea** [comment]
See my comment on https://github.com/xwikisas/application-meeting/issues/84#issuecomment-811919595 .
