### ISSUE TITLE
Meeting notes editor and display should take the full content column instead of 2/3

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-meeting#90]
Currently, the view and edit modes of the meeting are organized on 2 columns on large screens, 2/3 on the left for some metadata, the meeting plan and the meeting notes, and 1/3 reserved on the right for the participants column:

Here is a screenshot from a meeting in french:

View:
![image](https://user-images.githubusercontent.com/657716/143557506-7fa487aa-eb43-4bc7-a134-3c54f278ebef.png)

Edit:
![image](https://user-images.githubusercontent.com/657716/143557601-e4c34193-4050-4405-8f93-8104c575a1c1.png)

On these screenshots it's visible that the space on the right (the "participants" column) seems to remain empty at all times (view and edit) - I guess it would fill in if the participants list would be longer - while the content on the left is not taking the available space. Especially in edit mode, the editor is small and could be larger.

This task is about trying to find a layout that gives the full width of the content column to the meeting notes field, in view and edit modes.

**Comment by trrenty** [comment]
What do you think of this layout. 

View Page where I highlighted how the fields are grouped.
![image](https://user-images.githubusercontent.com/45433221/156021443-2b9c8874-bb27-472b-825b-1e9fcb44726c.png)

Edit Page:
![image](https://user-images.githubusercontent.com/45433221/156021716-a657a262-7246-4d44-8087-0f0b6fa7e7a7.png)
