### ISSUE TITLE
Errors in JS console which prevent calendar macro functioning in XWiki 14.1

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-meeting#92]
Environment: Windows 11 Pro 64bit, Firefox 98, using an instance of XWiki 14.1 on Tomcat 9.0.59/ PostgreSQL 14 with Meeting Application (Pro) 1.12.1

STEPS TO REPRODUCE
1. Go to Meetings home page
2. Click on "calendar" link

EXPECTED RESULTS

The user lands on CalendarView page where a calendar is displayed.

ACTUAL RESULTS

The calendar is not displayed. The following stacktrace is displayed in browser console:

```
GEThttp://localhost:1113/webjars/wiki:xwiki/momentjs/2.29.1/min/moment.min/min/moment.min.js
[[HTTP/1.1 404  250ms]]()
```
and

```
Uncaught Error: Script error for "moment/min/moment.min"
https://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    onScriptError http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    load http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    ...
    <anonymous> http://localhost:1113/bin/view/Meeting/CalendarView:726
[require.min.js:5:1795](http://localhost:1113/webjars/wiki%3Axwiki/requirejs/2.3.6/require.min.js?r=1)
```
and

```
Uncaught Error: Load timeout for modules: fullcalendar,gcal
https://requirejs.org/docs/errors.html#timeout
    makeError http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    ...
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
```
![Calendar_View_error](https://user-images.githubusercontent.com/32512703/159002856-6cc7376a-35a7-452a-9858-491fa1286225.png)

From my tests, the issue didn't reproduce on XWiki 13.10.3. 
Issue was reported also on Calendar Pro Application: https://github.com/xwikisas/application-mocca-calendar/issues/80

**Comment by trrenty** [comment]
#95 also fixed this issue. Closing it.
